spring:
  application:
    name: workflow-service

  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.sirp.workflow: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html

server:
  forward-headers-strategy: framework