server:
  port: 8080

spring:

  cloud:

    consul:
      host: localhost
      port: 8500

      discovery:
        service-name: api-gateway
        prefer-ip-address: true

    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

      routes:

        - id: user-service

          uri: lb://USER-SERVICE

          predicates:
            - Path=/api/v1/users/**

        - id: incident-service

          uri: lb://INCIDENT-SERVICE

          predicates:
            - Path=/incidents/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

