server:
  port: 8085

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/sirp_notification_db
    username: postgres
    password: root

  jpa:

    hibernate:
      ddl-auto: update

    show-sql: true

    properties:

      hibernate:
        format_sql: true

  kafka:

    bootstrap-servers: localhost:29092

    consumer:

      group-id: notification-service

      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:

        spring.json.trusted.packages: "*"

  cloud:

    consul:

      host: localhost

      port: 8500

      discovery:

        enabled: true

        register: true

        service-name: notification-service

  mail:

    host: smtp.gmail.com

    port: 587

    username: mayurvalte2017@gmail.com

    password: yvec kewf rhzs zcig

    properties:

      mail:

        smtp:

          auth: true

          starttls:

            enable: true

management:

  endpoint:

    health:

      show-details: always

  endpoints:

    web:

      exposure:

        include: health,info,metrics

springdoc:

  swagger-ui:

    path: /swagger-ui.html

  api-docs:

    path: /v3/api-docs
